### ISSUE TITLE
Bu-Ali Sina University website doesn't load

### ISSUE THREAD

**Issue by mkoushan** [ThomazPom/Moz-Ext-UltimaDark#99]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I am on a compatible (Desktop) browser that is up-to-date or explicitly listed as being compatible in the [README](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/blob/master/readme.md)
- [X] I'm reporting that UltimaDark is broken in a novel way that deserves it's own issue meaning it should not be added to [#6](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/6) [#7](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/7) [#8](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/8) or [#94](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/94)
- [X] This site is not listed in an existing issue or in [#6](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/6) [#7](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/7) [#8](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/8) or [#94](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/94)
- [X] I verified that I am on the latest version
- [X] I verified that ImageEdition, Caching, Service Worker Compatibility and the extension itself are all enabled and that I loaded the site cleanly by closing the tab and opening the URL in a new tab or I flushed it completely with [Tab Suspender](https://www.github.com/Hau-Hau/firefox-tab-suspender)
- [X] I tried disabling caching and refreshing the page several times and it is still broken.
- [X] I confirmed that the target site is not on the excluded sites list or a Mozilla domain on Firefox's protected site listin about:config
- [X] I've searched [known issues](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [README](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/blob/master/readme.md) and understand how and why to open an issue.

### Site URL

https://golestan.basu.ac.ir/forms/authenticateuser/main.htm

### Provide a description of what about the site is broken and attach screenshots at the bottom

Without UltimaDark:
![image](https://github.com/user-attachments/assets/8c468617-709b-4ce2-838a-282a0ff1bfb3)

With UltimaDark:
![image](https://github.com/user-attachments/assets/b01add11-38b7-491f-919a-dbd453766db4)

### Provide console logs

- [X] Go to about:debugging#/runtime/this-firefox
- [X] Click "Inspect" on UltimaDark
- [X] Clear the log and refresh the page that is broken
- [X] Copy the WHOLE output and insert it below

### Complete Log

```shell
https://bin.bloat.cat/?a5d1da2e0d6657b6#Geeq5wGxB9rHXSdC5iHHJCCBDyKUt5m6eKyaScLuhBQa
```

**Comment by ThomazPom** [comment]
Website apears offline from europe. 

Breaking page mistake were found and fixed in [1.5.67]. If you can check again, please report your results.
Thank you for your reporting.

**Comment by mkoushan** [comment]
Sadly it didn't. Well I'll try to look at your project, I'll work on it myself (Hopefully)

**Comment by ThomazPom** [comment]
It’s not well coded, as it started as an expermient. One day I’ll have to revues the architecture

**Comment by ThomazPom** [comment]
Architecture of the project has been entirely reviewed, among a lot of underlying logics. This issue might be solved. I cannot display Bu-Ali Sina University website from France, therefore i can't test.

**Comment by mkoushan** [comment]
No it's still broken, unfortunately right now I'm drowning in thousands of deadlines and I can't take a look at this, I'll try my best to find a time for it. Thanks for your great work again!
